'use client';

import { Suspense } from 'react';
import { GAME_REGISTRY } from '@/lib/mix-editor/game-registry';
import { useMixEditorStore } from '@/lib/mix-editor/mix-editor.store';

interface VariantThumbnailProps {
  gameId: string;
  variantId: string;
  index: number;
}

export function VariantThumbnail({ gameId, variantId, index }: VariantThumbnailProps) {
  const { mix, activeVariantId, selectVariant, removeVariant } = useMixEditorStore();

  const game = mix.games.find((g) => g.id === gameId);
  const variant = game?.variants.find((v) => v.id === variantId);

  if (!game || !variant) return null;

  const isActive = activeVariantId === variantId;
  const plugin = GAME_REGISTRY[game.type];
  const Thumbnail = plugin.ThumbnailComponent;

  return (
    <div
      className={`variant-thumbnail ${isActive ? 'variant-thumbnail--active' : ''}`}
      onClick={() => selectVariant(gameId, variantId)}
      role="button"
      tabIndex={0}
      onKeyDown={(e) => e.key === 'Enter' && selectVariant(gameId, variantId)}
    >
      {variant.isAutoGenerated && (
        <span className="variant-thumbnail__auto-badge" title="Auto-generovaná">★</span>
      )}
      <button
        type="button"
        className="variant-thumbnail__remove"
        onClick={(e) => {
          e.stopPropagation();
          removeVariant(gameId, variantId);
        }}
        disabled={game.variants.length <= 1}
        aria-label="Smazat variantu"
        title="Smazat variantu"
      >
        <i className="ti ti-x" />
      </button>
      <div className="variant-thumbnail__preview">
        <Suspense fallback={<div className="variant-thumbnail__loading" />}>
          <Thumbnail data={variant.data as never} isActive={isActive} />
        </Suspense>
      </div>
      <span className="variant-thumbnail__label">Varianta {index + 1}</span>
    </div>
  );
}
