/**
 * Central definition of query keys for TanStack Query.
 */
export const QUERY_KEYS = {
  courses:        () => ['courses'] as const,
  course:         (id: string) => ['courses', id] as const,
  courseSettings: (id: string) => ['courses', id, 'settings'] as const,
  lessons:        (courseId: string) => ['courses', courseId, 'lessons'] as const,
  lesson:         (id: string) => ['lessons', id] as const,
  blocks:         (lessonId: string) => ['lessons', lessonId, 'blocks'] as const,
  exercise:       (blockId: string) => ['blocks', blockId, 'exercise'] as const,
  accessCodes:    (courseId: string) => ['courses', courseId, 'access-codes'] as const,
  emailAccess:    (courseId: string) => ['courses', courseId, 'email-access'] as const,
  templates:           () => ['templates'] as const,
  courseDeletePreview: (id: string) => ['courses', id, 'delete-preview'] as const,
  deletedCourses:      (filter: object) => ['courses', 'deleted', filter] as const,
  accessCodesGlobal:   (filter: object) => ['access', 'codes', filter] as const,
  accessUserGrants:    (filter: object) => ['access', 'users', filter] as const,
  allLessons:  (filter: object) => ['lessons', 'all', filter] as const,
  lessonStats: (id: string) => ['lessons', id, 'stats'] as const,
  lessonUsers:  (id: string, filter: object) => ['lessons', id, 'users', filter] as const,
  blockContent:          (id: string) => ['blocks', id, 'content'] as const,
  accessRecordsPreview:  (courseId: string, ids: string[]) => ['courses', courseId, 'access-preview', ids] as const,
  lessonVocabulary:      (lessonId: string, filter: object) => ['lessons', lessonId, 'vocabulary', filter] as const,
  lessonVocabularyImport:(lessonId: string) => ['lessons', lessonId, 'vocabulary-import'] as const,
  lessonsForImport:      (excludeId: string) => ['lessons', 'for-import', excludeId] as const,
  lessonMix:             (lessonId: string) => ['lessons', lessonId, 'mix'] as const,
  practiceConfig:        (lessonId: string) => ['lessons', lessonId, 'practice-config'] as const,
  groups:                () => ['groups'] as const,
  group:                 (id: string) => ['groups', id] as const,
  groupsUserSearch:      (q: string) => ['groups', 'users', q] as const,
  courseAccessCodes:     (id: string) => ['courses', id, 'access-codes-list'] as const,
  groupCourses:          (id: string) => ['groups', id, 'courses'] as const,
  userDetail:            (id: string) => ['users', id] as const,
  userCourses:           (id: string) => ['users', id, 'courses'] as const,
} as const;
