/**
 * Zustand store of the Mix editor (game sequence, variants, ordering).
 */
import { create } from 'zustand';
import { v4 as uuid } from 'uuid';
import { VocabularyWord } from '@/lib/vocabulary/vocabulary.types';
import { GameData, GameType, LessonMix, SequenceGame } from './mix-editor.types';
import { GAME_REGISTRY } from './game-registry';
import { autoGenerateFullMix, validateMix } from './mix-editor.utils';
import { requestSentences, saveLessonMix } from './mix-editor.api';
import { GenerateContext } from '@/components/admin/mix-editor/games/shared/generate-result';
import { useUIStore } from '@/lib/stores/ui.store';

const MAX_GAMES = 20;

interface MixEditorState {
  mix: LessonMix;
  lessonWords: VocabularyWord[];

  generationWords: VocabularyWord[];
  lessonTitle: string;
  courseId: string;
  courseTitle: string;

  activeGameId: string | null;
  activeVariantId: string | null;

  isDirty: boolean;
  isSaving: boolean;
  isGenerating: boolean;

  initMix: (mix: LessonMix, words: VocabularyWord[], lessonTitle: string, courseId: string, courseTitle: string) => void;
  setGenerationWords: (words: VocabularyWord[]) => void;

  addGame: (type: GameType, afterId?: string) => void;
  removeGame: (gameId: string) => void;
  reorderGames: (activeId: string, overId: string) => void;
  selectGame: (gameId: string) => void;
  toggleRandomizer: () => void;
  setXp: (xp: number) => void;

  addVariant: (gameId: string) => void;
  removeVariant: (gameId: string, variantId: string) => void;
  selectVariant: (gameId: string, variantId: string) => void;
  updateVariantData: (gameId: string, variantId: string, data: GameData) => void;

  autoGenerateVariant: (gameId: string) => Promise<void>;
  autoGenerateAll: () => Promise<void>;

  saveMix: () => Promise<void>;
}

function makeEmptyVariant(type: GameType) {
  const plugin = GAME_REGISTRY[type];
  return { id: uuid(), data: plugin.createEmpty(), isAutoGenerated: false, generatedAt: null };
}

function buildGenerateContext(get: () => MixEditorState): GenerateContext {
  const { generationWords, lessonWords, mix } = get();
  const words = generationWords.length > 0 ? generationWords : lessonWords;
  return {
    words,
    lessonId: mix.lessonId,
    requestSentences: (kind, count) => requestSentences(mix.lessonId, kind, count),
  };
}

export const useMixEditorStore = create<MixEditorState>((set, get) => ({
  mix: {
    id: '',
    lessonId: '',
    games: [],
    isRandomOrder: false,
    xp: 100,
    createdAt: '',
    updatedAt: '',
  },
  lessonWords: [],
  generationWords: [],
  lessonTitle: '',
  courseId: '',
  courseTitle: '',

  activeGameId: null,
  activeVariantId: null,

  isDirty: false,
  isSaving: false,
  isGenerating: false,

  initMix: (mix, words, lessonTitle, courseId, courseTitle) =>
    set({
      mix,
      lessonWords: words,

      generationWords: words,
      lessonTitle,
      courseId,
      courseTitle,
      activeGameId: null,
      activeVariantId: null,
      isDirty: false,
    }),

  setGenerationWords: (words) => set({ generationWords: words }),

  addGame: (type, afterId) => {
    const { mix } = get();
    if (mix.games.length >= MAX_GAMES) return;

    const variant = makeEmptyVariant(type);
    const newGame: SequenceGame = {
      id: uuid(),
      type,
      order: mix.games.length + 1,
      variants: [variant],
      activeVariantId: variant.id,
    };

    let games: SequenceGame[];
    if (afterId) {
      const idx = mix.games.findIndex((g) => g.id === afterId);
      games = [...mix.games.slice(0, idx + 1), newGame, ...mix.games.slice(idx + 1)];
    } else {
      games = [...mix.games, newGame];
    }

    games = games.map((g, i) => ({ ...g, order: i + 1 }));
    set({ mix: { ...mix, games }, activeGameId: newGame.id, activeVariantId: variant.id, isDirty: true });
  },

  removeGame: (gameId) => {
    const { mix, activeGameId } = get();
    const games = mix.games.filter((g) => g.id !== gameId).map((g, i) => ({ ...g, order: i + 1 }));
    const newActiveId = activeGameId === gameId ? (games[0]?.id ?? null) : activeGameId;
    set({ mix: { ...mix, games }, activeGameId: newActiveId, isDirty: true });
  },

  reorderGames: (activeId, overId) => {
    const { mix } = get();
    const activeIdx = mix.games.findIndex((g) => g.id === activeId);
    const overIdx = mix.games.findIndex((g) => g.id === overId);
    if (activeIdx === -1 || overIdx === -1) return;
    const games = [...mix.games];
    const [moved] = games.splice(activeIdx, 1);
    games.splice(overIdx, 0, moved);
    const reordered = games.map((g, i) => ({ ...g, order: i + 1 }));
    set({ mix: { ...mix, games: reordered }, isDirty: true });
  },

  selectGame: (gameId) => {
    const { mix } = get();
    const game = mix.games.find((g) => g.id === gameId);
    if (!game) return;
    set({ activeGameId: gameId, activeVariantId: game.activeVariantId });
  },

  toggleRandomizer: () =>
    set((s) => ({ mix: { ...s.mix, isRandomOrder: !s.mix.isRandomOrder }, isDirty: true })),

  setXp: (xp) =>
    set((s) => ({ mix: { ...s.mix, xp }, isDirty: true })),

  addVariant: (gameId) => {
    const { mix } = get();
    const game = mix.games.find((g) => g.id === gameId);
    if (!game) return;
    const variant = makeEmptyVariant(game.type);
    const games = mix.games.map((g) =>
      g.id === gameId ? { ...g, variants: [...g.variants, variant], activeVariantId: variant.id } : g
    );
    set({ mix: { ...mix, games }, activeVariantId: variant.id, isDirty: true });
  },

  removeVariant: (gameId, variantId) => {
    const { mix } = get();
    const game = mix.games.find((g) => g.id === gameId);
    if (!game || game.variants.length <= 1) return;
    const variants = game.variants.filter((v) => v.id !== variantId);
    const newActiveVariantId = game.activeVariantId === variantId ? variants[0].id : game.activeVariantId;
    const games = mix.games.map((g) =>
      g.id === gameId ? { ...g, variants, activeVariantId: newActiveVariantId } : g
    );
    set({ mix: { ...mix, games }, activeVariantId: newActiveVariantId, isDirty: true });
  },

  selectVariant: (gameId, variantId) => {
    const { mix } = get();
    const games = mix.games.map((g) =>
      g.id === gameId ? { ...g, activeVariantId: variantId } : g
    );
    set({ mix: { ...mix, games }, activeGameId: gameId, activeVariantId: variantId });
  },

  updateVariantData: (gameId, variantId, data) => {
    const { mix } = get();
    const games = mix.games.map((g) =>
      g.id !== gameId
        ? g
        : {
            ...g,
            variants: g.variants.map((v) => (v.id === variantId ? { ...v, data } : v)),
          }
    );
    set({ mix: { ...mix, games }, isDirty: true });
  },

  autoGenerateVariant: async (gameId) => {
    const { mix } = get();
    const game = mix.games.find((g) => g.id === gameId);
    if (!game) return;
    const plugin = GAME_REGISTRY[game.type];
    const existingData = game.variants.map((v) => v.data);

    set({ isGenerating: true });
    try {
      const result = await plugin.autoGenerate(buildGenerateContext(get), existingData as never[]);
      if (!result.ok) {
        useUIStore.getState().showToast(result.reason, 'error');
        return;
      }
      const variant = {
        id: uuid(),
        data: result.data,
        isAutoGenerated: true,
        generatedAt: new Date().toISOString(),
      };
      const current = get().mix;
      const games = current.games.map((g) =>
        g.id === gameId
          ? { ...g, variants: [...g.variants, variant], activeVariantId: variant.id }
          : g
      );
      set({ mix: { ...current, games }, activeVariantId: variant.id, isDirty: true });
      useUIStore.getState().showToast('Varianta vygenerována');
    } catch (err) {
      useUIStore.getState().showToast((err as Error).message || 'Generování selhalo', 'error');
    } finally {
      set({ isGenerating: false });
    }
  },

  autoGenerateAll: async () => {
    const { mix } = get();
    set({ isGenerating: true });
    const toast = useUIStore.getState().showToast;

    try {
      if (mix.games.length === 0) {
        const { games, errors } = await autoGenerateFullMix(buildGenerateContext(get));
        if (games.length === 0) {
          toast(errors[0] ?? 'Nepodařilo se nic vygenerovat — zkontroluj slovní zásobu.', 'error');
          return;
        }
        const current = get().mix;
        set({
          mix: { ...current, games },
          activeGameId: games[0].id,
          activeVariantId: games[0].activeVariantId,
          isDirty: true,
        });
        if (errors.length > 0) {
          toast(`Vygenerováno. Přeskočeno (${errors.length}): ${errors[0]}`, 'info');
        } else {
          toast('Mix vygenerován');
        }
      } else {
        const ctx = buildGenerateContext(get);
        const errors: string[] = [];
        let games = [...mix.games];
        for (const game of mix.games) {
          const plugin = GAME_REGISTRY[game.type];
          const existingData = game.variants.map((v) => v.data);
          try {
            const result = await plugin.autoGenerate(ctx, existingData as never[]);
            if (!result.ok) {
              errors.push(`${plugin.label}: ${result.reason}`);
              continue;
            }
            const variant = { id: uuid(), data: result.data, isAutoGenerated: true, generatedAt: new Date().toISOString() };
            games = games.map((g) =>
              g.id === game.id
                ? { ...g, variants: [...g.variants, variant], activeVariantId: variant.id }
                : g
            );
          } catch (err) {
            errors.push(`${plugin.label}: ${(err as Error).message}`);
          }
        }
        const current = get().mix;
        set({ mix: { ...current, games }, isDirty: true });
        if (errors.length > 0) {
          toast(errors[0], 'error');
        } else {
          toast('Varianty vygenerovány');
        }
      }
    } finally {
      set({ isGenerating: false });
    }
  },

  saveMix: async () => {
    const { mix } = get();
    const errors = validateMix(mix);
    if (errors.length > 0) {
      useUIStore.getState().showToast(errors[0], 'error');
      return;
    }
    set({ isSaving: true });
    try {
      const saved = await saveLessonMix(mix.lessonId, mix);
      set({ mix: saved, isDirty: false });
      useUIStore.getState().showToast('Mix byl uložen');
    } catch {
      useUIStore.getState().showToast('Chyba při ukládání', 'error');
    } finally {
      set({ isSaving: false });
    }
  },
}));
