import { VocabularyWord } from '@/lib/vocabulary/vocabulary.types';
import { GenerateContext, GenerateResult } from '@/components/admin/mix-editor/games/shared/generate-result';

export type GameType =
  | 'connector'
  | 'fill_in'
  | 'multiple_choice'
  | 'listening'
  | 'word_order'
  | 'translation'
  | 'word_transform';

export interface GameVariant {
  id: string;
  data: GameData;
  isAutoGenerated: boolean;
  generatedAt: string | null;
}

export interface SequenceGame {
  id: string;
  type: GameType;
  order: number;
  variants: GameVariant[];
  activeVariantId: string;
}

export interface LessonMix {
  id: string;
  lessonId: string;
  games: SequenceGame[];
  isRandomOrder: boolean;
  xp: number;
  createdAt: string;
  updatedAt: string;
}

export interface GamePlugin<TData extends GameData> {
  type: GameType;
  label: string;
  icon: string;
  color: string;
  description: string;

  createEmpty: () => TData;
  autoGenerate: (ctx: GenerateContext, existingVariants: TData[]) => Promise<GenerateResult<TData>>;
  validate: (data: TData) => ValidationResult;
  estimateTime: (data: TData) => number;

  EditorComponent: React.ComponentType<GameEditorProps<TData>>;
  PreviewComponent: React.ComponentType<GamePreviewProps<TData>>;
  ThumbnailComponent: React.ComponentType<GameThumbnailProps<TData>>;
}

export interface GameEditorProps<TData> {
  data: TData;
  onChange: (data: TData) => void;
  lessonWords: VocabularyWord[];
}

export interface GamePreviewProps<TData> {
  data: TData;
  mode: 'thumbnail' | 'full';
}

export interface GameThumbnailProps<TData> {
  data: TData;
  isActive: boolean;
}

export type GameData = any;

export interface ValidationResult {
  valid: boolean;
  errors: string[];
}

export type GamePluginRegistry = {
  [K in GameType]: GamePlugin<GameData>;
};
