import { GAME_REGISTRY } from './game-registry';
import { GameType, LessonMix, SequenceGame } from './mix-editor.types';
import { GenerateContext } from '@/components/admin/mix-editor/games/shared/generate-result';
import { v4 as uuid } from 'uuid';

export function estimateTotalTime(mix: LessonMix): number {
  return mix.games.reduce((total, game) => {
    const plugin = GAME_REGISTRY[game.type];
    const maxTime = game.variants.reduce((max, v) => {
      const t = plugin.estimateTime(v.data);
      return t > max ? t : max;
    }, 0);
    return total + maxTime;
  }, 0);
}

export function formatTime(seconds: number): string {
  if (seconds < 60) return `${seconds} s`;
  const min = Math.round(seconds / 60);
  return `~${min} min`;
}

export function validateMix(mix: LessonMix): string[] {
  const errors: string[] = [];

  if (mix.games.length === 0) {
    errors.push('Mix musí obsahovat alespoň jednu hru');
    return errors;
  }

  for (const game of mix.games) {
    const plugin = GAME_REGISTRY[game.type];

    if (game.variants.length === 0) {
      errors.push(`Hra "${plugin.label}" nemá žádnou variantu`);
      continue;
    }

    for (const [i, variant] of game.variants.entries()) {
      const result = plugin.validate(variant.data);
      if (!result.valid) {
        errors.push(`${plugin.label} varianta ${i + 1}: ${result.errors.join(', ')}`);
      }
    }
  }

  return errors;
}

async function makeGame(
  type: GameType,
  ctx: GenerateContext,
  variantCount = 2,
): Promise<{ game?: SequenceGame; error?: string }> {
  const plugin = GAME_REGISTRY[type];
  const variants = [];
  const existingData: unknown[] = [];
  let lastReason = '';

  for (let i = 0; i < variantCount; i++) {
    let result;
    try {
      result = await plugin.autoGenerate(ctx, existingData as never[]);
    } catch (err) {
      lastReason = (err as Error).message;
      break;
    }
    if (!result.ok) {
      lastReason = result.reason;
      break;
    }
    existingData.push(result.data);
    variants.push({
      id: uuid(),
      data: result.data,
      isAutoGenerated: true,
      generatedAt: new Date().toISOString(),
    });
  }

  if (variants.length === 0) {
    return { error: `${plugin.label}: ${lastReason}` };
  }
  return { game: { id: uuid(), type, order: 0, variants, activeVariantId: variants[0].id } };
}

export async function autoGenerateFullMix(
  ctx: GenerateContext,
): Promise<{ games: SequenceGame[]; errors: string[] }> {
  const candidates: [GameType, number][] = [
    ['connector', 2],
    ['fill_in', 2],
    ['multiple_choice', 2],
    ['word_order', 1],
    ['translation', 1],
    ['word_transform', 1],
    ['listening', 1],
  ];

  const games: SequenceGame[] = [];
  const errors: string[] = [];
  let order = 1;

  for (const [type, variantCount] of candidates) {
    const { game, error } = await makeGame(type, ctx, variantCount);
    if (game) {
      game.order = order++;
      games.push(game);
    } else if (error) {
      errors.push(error);
    }
  }

  return { games, errors };
}
